[feat] initial commit npm install basic architecture
HUB-Lyon/Plateforme_HUB pull request #1
Opened 2023-11-13 13:50 UTC by Tristancalard

2023-11-13 13:52 UTC, RainproDash approved these changes

2023-11-13 14:37 UTC, Tristancalard commented
back to current work and remove view (only backend)

2023-11-14 10:36 UTC, alanschnegg commented on Backend/routes/project/project.js
> +        const data = await get_project(req.body.id);
You don't have a body in a get request

2023-11-14 11:00 UTC, thmarinho requested changes
Comments has not been dusplicated on pupose, each one os them should be apply on many lines
Rename your folder 'backend' (no capitalize)

2023-11-14 11:00 UTC, thmarinho commented on Backend/app.js
> +var authRouter = require('./routes/auth/auth');
use 'const' instead ot 'var'

2023-11-14 11:00 UTC, thmarinho commented on Backend/app.js
> +});
This is useless, express will throw a 404 if the request cannot be handled

2023-11-14 11:00 UTC, thmarinho commented on Backend/app.js
> +});
Remove this, used by the former view system

2023-11-14 11:00 UTC, thmarinho commented on Backend/package-lock.json
Delete this and add it to .gitignore

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/auth/auth.js
> +router.get('/acquireToken', authProvider.acquireToken({
change the route to `/token`, the HTTP verb already told us you want to GET it

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/index.js
Delete this file

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/inventory/inventory.js
> +        res.status(500).json({ error: 'Erreur lors de la récupération des données' });
Error messages should be in english

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/inventory/inventory.js
> +        if (data.length == 0) {
Your query is wrong, you should not retrieve an array, one id = one DB entry

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/inventory/inventory.js
> +        res.json({"msg": "Supression de l'objet " + req.params.id + " réussie"});
Use code 204, nothig returned

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/inventory/inventory.js
> +        res.json({"msg": "Création de l'objet " + req.body.name + " réussie"});
Use 201, a document has been created at this point

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/inventory/inventory.query.js
> +        return result;
return await db`SELECT * FROM inventory`

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/inventory/inventory.query.js
> +}
You should edit the field received, not all of them
If I don't send 'quantity', this will set the value to NULL

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/project/project.js
> +        const data = await get_project(req.body.id);
use plurar on 'project'
Why are you using an id ?
AND WHY ARE YOU USING A BODY IN A GET ?

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/project/project.js
> +        const data = await get_project_by_id(req.body.id, req.params.id);
ok, why is there two param here ?
Same error as before, you should not get an array from this call

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/project/project.js
> +});
This won't work, every call in this route will go on the `/:id` route
Moreover, this should a query on the GET all

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/project/project.js
> +});
Why are you using an id on a POST route ?

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/project/project.js
> +        res.json({"msg": "Création du projet " + req.body.name + " réussie"});
Use backticks (`) to make a nicer concatenation

2023-11-14 11:00 UTC, thmarinho commented on Backend/routes/project/project.query.js
> +        await db`INSERT INTO project (id, name, description, leader_id, member_id, status) VALUES (${sql`${id}`}, ${sql`${name}`}, ${sql`${description}`}, ${sql`${leader_id}`}, ${sql`${member_id}`},
use plurar on 'member', it's an array

2023-11-14 14:00 UTC, closed without merging