[feat] init workflow ci/cd
HUB-Lyon/Plateforme_HUB pull request #16
Opened 2023-11-23 11:51 UTC by lucas-debize

2023-11-23 12:58 UTC, alanschnegg requested changes

2023-11-23 12:58 UTC, alanschnegg commented on .github/workflows/ci-cd.yml
> +      run: npm test
npm run test

2023-11-23 12:58 UTC, alanschnegg commented on .github/workflows/ci-cd.yml
> +        node-version: 21
Wrong version

2023-11-23 12:58 UTC, alanschnegg commented on .github/workflows/ci-cd.yml
> +        node-version: 21
Wrong version

2023-11-23 12:58 UTC, alanschnegg commented on .github/workflows/ci-cd.yml
> +      run: npm install next
Wrong order

2023-11-23 14:24 UTC, alanschnegg requested changes

2023-11-23 14:24 UTC, alanschnegg commented on backend/package.json
> +    "lint": "exit 0",
Wait for the linter PR and add it to this one

2023-11-23 14:24 UTC, alanschnegg commented on frontend/package.json
> +    "test": "exit 0"
same

2023-11-23 16:07 UTC, alanschnegg approved these changes

2023-11-23 16:08 UTC, thmarinho requested changes

2023-11-23 16:08 UTC, thmarinho commented on .github/workflows/test.yml
> +      - develop
Test with this :
```yml
on:
  push:
  branches:
```

2023-11-23 16:08 UTC, thmarinho commented on .github/workflows/test.yml
> +      run: npm install next
Why do you need this ?

2023-11-23 16:08 UTC, thmarinho commented on .github/workflows/test.yml
> +      run: npm run lint
Run the linter before building, this a more common error

2023-11-23 16:08 UTC, thmarinho commented on .github/workflows/test.yml
> +      run: npm run lint
Same thing for here

2023-11-23 16:08 UTC, thmarinho commented on .github/workflows/test.yml
> +      run: npm run test
Do'nt run tests until frontend has some

2023-11-24 13:01 UTC, lucas-debize commented on .github/workflows/test.yml
> +      - develop
not working without " -'*' "

2023-11-24 13:56 UTC, thmarinho requested changes

2023-11-24 13:56 UTC, thmarinho commented on .github/workflows/test.yml
> +      run: npm run test
Delete this, backend's tests hasn't been merged

2023-11-24 13:56 UTC, thmarinho commented on backend/package.json
> +    "test": "echo \"Error: no test specified\" && exit 0",
Restore your changes on this line

2023-11-24 14:14 UTC, thmarinho requested changes

2023-11-24 14:14 UTC, thmarinho commented on frontend/pages/component/utils.tsx
>  }
You should remove the `default`  or rename the file, `utils.tsx` -> `classNames.tsx` for instance

2023-11-24 14:26 UTC, thmarinho approved these changes

2023-11-24 14:27 UTC, merged