[feat] Unit tests
HUB-Lyon/Plateforme_HUB pull request #27
Opened 2023-11-29 14:51 UTC by Tristancalard

Add inventory routes Unit tests
Add projects routes Unit tests
Do :
    npm run test

2023-11-29 16:33 UTC, thmarinho requested changes

2023-11-29 16:33 UTC, thmarinho commented on backend/src/test/inventory.test.ts
> +        expect(res.text).to.equal('[{"id":1,"name":"name","image":"image","category":"category","quantity":2,"available":true,"description":"description"}]');
```suggestion
        const data = {
            id: 1,
            name: 'name',
            image: 'image',
            category: 'category',
            quantity: 2,
            available: true,
            description: 'description',
        };
        await respository.save(data);
        
        const res = await chari.request(app).get('/inventory')
        expect(res).to.have.status(200)
        expect(res.body).to.beDefined()
        expect(res.body.id).to.be(data.id)
        [...]
```

2023-11-30 14:21 UTC, thmarinho requested changes
Comments should be applied everywhere

2023-11-30 14:21 UTC, thmarinho commented on backend/src/test/inventory.test.ts
> +            id: 1,
delete this

2023-11-30 14:21 UTC, thmarinho commented on backend/src/test/inventory.test.ts
> +        expect(res.body[0].id).to.equal(Number(data.id));
.to.be.defined

2023-11-30 14:21 UTC, thmarinho commented on backend/src/test/inventory.test.ts
> +    it('should return all items from the inventory on /inventory GET', async () => {
test with multiple values, this is a get all route

2023-11-30 14:27 UTC, Tristancalard commented on backend/src/test/inventory.test.ts
> +        expect(res.body[0].id).to.equal(Number(data.id));
don't exist in chai

2023-12-04 10:12 UTC, thmarinho requested changes
Comments should applied on each file

2023-12-04 10:12 UTC, thmarinho commented on backend/src/test/inventory.test.ts
> +        expect(res.body[0].id).to.equal(1);
to.be.defined

2023-12-04 10:12 UTC, thmarinho commented on backend/src/test/inventory.test.ts
> +        const res = await chai.request(app).get('/inventory/3');
Do not expect it to be id=3, look at the repository.save return value

2023-12-04 10:12 UTC, thmarinho commented on backend/src/test/inventory.test.ts
You should not use hardcoded ids.
If a test is added in the middle of this file, everything will blow up

2023-12-04 14:28 UTC, thmarinho requested changes
`id++` è.é

2023-12-04 16:14 UTC, thmarinho approved these changes

2023-12-05 09:04 UTC, merged