PR : dark mode
HUB-Lyon/Plateforme_HUB pull request #31
Opened 2023-12-04 15:47 UTC by LaolouRavon-Laforest

2023-12-04 16:30 UTC, thmarinho requested changes
Will look at this when #30 will be merged

2023-12-04 16:35 UTC, thmarinho requested changes

2023-12-04 16:35 UTC, thmarinho commented on frontend/pages/project.tsx
> +        <div className="gb-red-600 dark:gb-grey-500">
gb ?

2023-12-04 16:35 UTC, thmarinho commented on frontend/styles/globals.css
> +}
Not used

2023-12-04 16:35 UTC, thmarinho commented on frontend/pages/component/RootLayout.tsx
> +        document.documentElement.classList.toggle('dark', newTheme === 'dark');
`document.documentElement` è.é

2023-12-04 16:35 UTC, thmarinho commented on frontend/pages/component/RootLayout.tsx
> +        return false;
```suggestion
        return savedTheme === 'dark'
```
?

2023-12-04 16:35 UTC, thmarinho commented on frontend/tailwind.config.ts
> +    darkMode: 'class',
move this above `content`

2023-12-04 16:35 UTC, thmarinho commented on frontend/pages/component/NavBar.tsx
> +                                        </div>
Duplicated from below

2023-12-04 16:35 UTC, thmarinho commented on frontend/pages/component/NavBar.tsx
> +                                                        </div>
Duplicated from above

2023-12-05 09:13 UTC, alanschnegg requested changes

2023-12-05 09:13 UTC, alanschnegg commented on frontend/pages/component/NavBar.tsx
> +import { isDarkTheme } from './RootLayout';
Make only one import

2023-12-05 09:13 UTC, alanschnegg commented on frontend/pages/component/NavBar.tsx
> +    const [darkTheme, setDarkTheme] = useState(isDarkTheme());
Why define an useState to save if theme dark is used when you already have a function for that ?
You even use this function to set the default value

2023-12-05 09:13 UTC, alanschnegg commented on frontend/pages/component/NavBar.tsx
> +    };
Remove this and the useState and just use 'toggleTheme' and 'isDarkTheme' from the import

2023-12-11 09:58 UTC, thmarinho commented
Closing PR

2023-12-11 09:58 UTC, closed without merging