[feat] connection management with microsoft
HUB-Lyon/Plateforme_HUB pull request #36
Opened 2023-12-13 15:17 UTC by lucas-debize

2023-12-13 15:52 UTC, thmarinho requested changes
Aren't you missing somethin like this ?
```jsx
      <AuthenticatedTemplate>
        <PageLayout />
      </AuthenticatedTemplate>

      <UnauthenticatedTemplate>
        <Login />
      </UnauthenticatedTemplate>
   ```

2023-12-13 15:52 UTC, thmarinho commented on frontend/components/NavBar.tsx
> +import Link from '../node_modules/next/link';
No imports from node_modules

2023-12-13 15:52 UTC, thmarinho commented on frontend/components/msalConfig.tsx
> +        redirectUri: process.env.REDIRECT_URI || 'http://localhost:3001/auth/redirect',
Is this a prank ?

2023-12-20 10:52 UTC, thmarinho requested changes

2023-12-20 10:52 UTC, thmarinho commented on frontend/components/msalConfig.tsx
> +        redirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI || '',
```suggestion
        clientId: process.env.NEXT_PUBLIC_CLIENT_ID,
        authority: 'https://login.microsoftonline.com/' + (process.env.NEXT_PUBLIC_TENANT_ID),
        redirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI,
```

2023-12-20 10:52 UTC, thmarinho commented on frontend/pages/_app.tsx
> +                    </RootLayout>
```suggestion
                    <RootLayout>
                        <Component {...pageProps} />
                                    <ToastContainer 
                                        position= 'top-right'
                                        autoClose= {5000}
                                        hideProgressBar= {false}
                                        closeOnClick= {true}
                                        pauseOnHover= {true}
                                        draggable= {false}
                                    />
                    </RootLayout>
```

2023-12-20 11:03 UTC, lucas-debize commented on frontend/components/msalConfig.tsx
> +        redirectUri: process.env.NEXT_PUBLIC_REDIRECT_URI || '',
can't remove this without an error with msal definition

2023-12-20 12:18 UTC, thmarinho approved these changes

2023-12-20 12:23 UTC, merged