[feat] Article page
HUB-Lyon/Plateforme_HUB pull request #37
Opened 2023-12-14 09:58 UTC by Tristancalard

2023-12-14 10:13 UTC, alanschnegg requested changes

2023-12-14 10:13 UTC, alanschnegg commented on frontend/config.js
> +};
'apiUrl_hub' should be in .env

2023-12-14 10:13 UTC, alanschnegg commented on frontend/pages/article.tsx
> +            }),
STOP STRINGIFY YOUR BODY 
Body should be a json object

2023-12-14 10:13 UTC, alanschnegg commented on frontend/pages/article.tsx
> +            }),
Same

2023-12-14 10:13 UTC, alanschnegg commented on frontend/pages/article.tsx
> +        setValue2(newValue);
Better variable name, need explicit one

2023-12-14 10:13 UTC, alanschnegg commented on frontend/pages/article.tsx
> +            </Modal>
Move this to a component

2023-12-15 13:04 UTC, RainproDash requested changes

2023-12-15 13:04 UTC, RainproDash commented on backend/src/app.ts
> +import articleRouter from './routes/article/router_article.js';
file should be name with . not with _

2023-12-15 13:12 UTC, RainproDash approved these changes

2023-12-18 09:35 UTC, thmarinho requested changes

2023-12-18 09:35 UTC, thmarinho commented on backend/src/app.ts
> +import articleRouter from './routes/article/router.article.js';
```suggestion
import articleRouter from './routes/article/router.articles.js';
```

2023-12-18 09:35 UTC, thmarinho commented on backend/src/config/db.ts
> +import { Article } from '../entity/article.js';
Move it upward w/ other entities

2023-12-18 09:35 UTC, thmarinho commented on frontend/components/dialog.tsx
> +import { Dialog, Transition} from '@headlessui/react';
```suggestion
import React, { Fragment } from 'react';
import dynamic from 'next/dynamic';
import { Dialog, Transition} from '@headlessui/react';
import 'react-quill/dist/quill.snow.css';

```

2023-12-18 09:35 UTC, thmarinho commented on frontend/pages/article.tsx
> +        },
```suggestion
```

2023-12-18 09:35 UTC, thmarinho commented on frontend/pages/article.tsx
> +        },
```suggestion
```

2023-12-18 09:35 UTC, thmarinho commented on frontend/pages/article.tsx
> +            }),
```suggestion
{
  name,
  content,
}
```

2023-12-18 09:37 UTC, alanschnegg approved these changes

2023-12-20 10:17 UTC, thmarinho approved these changes

2023-12-20 10:18 UTC, merged