[feat] Connection Microsoft
HUB-Lyon/Plateforme_HUB pull request #7
Opened 2023-11-15 14:50 UTC by Tristancalard

2023-11-15 18:37 UTC, thmarinho requested changes
Have this routes been tested ? You should be able to get an Office token allowing to get log on the intranet for example

2023-11-15 18:37 UTC, thmarinho commented on backend/src/app.ts
> +app.use(logger('dev'));
Should adapt to each deployment stage (dev, preprod, prod etc.)

2023-11-15 18:37 UTC, thmarinho commented on backend/src/routes/users/users.query.ts
> +    console.log(`Requête effectuée à ${endpoint} à : ` + new Date().toString());
Should be in english. Moreover, that's not necessary, you're using a logger above

2023-11-15 18:37 UTC, thmarinho commented on backend/src/routes/users/users.query.ts
> +        return response.data;
make it using fetch, axios will only make the app bigger

2023-11-15 18:37 UTC, thmarinho commented on backend/src/routes/users/users.ts
Rename this file, we should know it's the router

2023-11-15 18:37 UTC, thmarinho commented on backend/src/routes/users/users.query.ts
> + */
Remove this kind of comments, you'll propably use another documentation manager

2023-11-15 18:37 UTC, thmarinho commented on backend/src/routes/users/users.ts
> +});
Why is there some `res.render` ? You're backend should not send views

2023-11-16 13:14 UTC, alanschnegg requested changes

2023-11-16 13:14 UTC, alanschnegg commented on backend/src/app.ts
> +const logger_mode = 1;
Should be in .env

2023-11-16 13:14 UTC, alanschnegg commented on backend/src/routes/users/users.query.ts
>          const response: AxiosResponse = await axios.get(endpoint, options);
Replace Axios with fetch

2023-11-16 13:21 UTC, thmarinho requested changes

2023-11-16 13:21 UTC, thmarinho commented on backend/src/app.ts
> +app.use(logger(logger_mode ? 'dev' : 'common'));
`process.env.NODE_ENV === 'prod' ? 'dev : 'common'`

2023-11-16 15:24 UTC, Tristancalard commented
C'est bon :+1:

2023-11-16 16:05 UTC, thmarinho commented
Remove the comments from the Microsoft files, the code is explicit, you don't need to say 'fetching this route' on a request

2023-11-16 16:05 UTC, thmarinho requested changes
Remove the comments from the Microsoft files, the code is explicit, you don't need to say 'fetching this route' on a request

2023-11-16 16:11 UTC, thmarinho commented on backend/src/routes/users/users.query.ts
> +    console.log(`Request made to ${endpoint} at : ` + new Date().toString());
This line should still be deleted

2023-11-17 10:04 UTC, thmarinho requested changes

2023-11-17 10:04 UTC, thmarinho commented on backend/src/app.ts
> +app.use(logger(process.env.NODE_ENV === 'prod' ? 'dev' : 'common'));
```js
app.use(process.env.NODE8ENV === 'prod' ? 'common' : 'dev')
```

2023-11-17 13:45 UTC, alanschnegg approved these changes

2023-11-17 14:05 UTC, thmarinho approved these changes

2023-11-17 14:06 UTC, merged