[feat] swagger for auth routes
HUB-Lyon/Plateforme_HUB pull request #8
Opened 2023-11-21 09:31 UTC by Tristancalard

2023-11-21 14:18 UTC, thmarinho requested changes
![image](https://github.com/HUB-Lyon/Plateforme_HUB/assets/40118153/d8a98730-8773-4a9d-9803-54349f5c5adc)

2023-11-21 14:28 UTC, thmarinho requested changes

2023-11-21 14:28 UTC, thmarinho commented on backend/src/app.ts
> +    title: 'Express API',
Use a proper title

2023-11-21 14:28 UTC, thmarinho commented on backend/src/app.ts
> +    secure: false,
Fix identation

2023-11-21 14:28 UTC, thmarinho commented on backend/src/app.ts
> +app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, { explorer: true }));
use the /swagger route instead

2023-11-21 14:28 UTC, thmarinho commented on backend/src/app.ts
> +const swaggerSpec = swaggerJSDoc(options);
Don't declare options in a variable, just send the object in the `swaggerJSDoc`

2023-11-22 13:03 UTC, thmarinho requested changes

2023-11-22 13:03 UTC, thmarinho commented on backend/src/app.ts
> +import swaggerUi from 'swagger-ui-express';
Move this with the other package imports

2023-11-22 13:03 UTC, thmarinho commented on backend/src/app.ts
> +
Don't declare `swaggerDefinition` as a variable, just send the object in the `swaggerJSDoc`

2023-11-22 13:03 UTC, thmarinho commented on .gitignore
> -.env.dev
Keep this line

2023-11-22 13:03 UTC, thmarinho commented on backend/.env.template
> +
Remove empty lines

2023-11-22 13:03 UTC, thmarinho commented on backend/src/routes/auth/auth.ts
> +    successRedirect: '/auth/token'
Did you try this configuration ? Changing a redirectUrl can't broke a lot of things

2023-11-22 13:03 UTC, thmarinho commented on backend/src/routes/auth/auth.ts
> +    successRedirect: '/'
Same question here

2023-11-22 13:07 UTC, Tristancalard commented on backend/src/routes/auth/auth.ts
> +    successRedirect: '/auth/token'
yes it's work

2023-11-22 13:08 UTC, Tristancalard commented on backend/src/routes/auth/auth.ts
> +    successRedirect: '/'
yes it's work

2023-11-22 13:10 UTC, Tristancalard commented on backend/src/app.ts
> +
Error: Missing or invalid input: 'options.swaggerDefinition' or 'options.definition' is required
 I need it

2023-11-22 13:17 UTC, thmarinho requested changes

2023-11-22 13:17 UTC, thmarinho commented on backend/src/app.ts
> +
```js
const swaggerSpec = swaggerJSDoc({
  swaggerDefinition : {
  openapi: '3.0.0',
  info: {
    title: 'Plateforme HUB',
    version: '1.0.0',
  },
},
  apis: [`dist/routes/**/*.js`],
});
```

2023-11-22 13:25 UTC, thmarinho approved these changes

2023-11-22 13:29 UTC, alanschnegg approved these changes

2023-11-22 14:17 UTC, merged